### ISSUE TITLE
Unsound octagon analysis due to limited environment

### ISSUE THREAD

**Issue by julbinb** [cuplv/dai#10]
https://github.com/cuplv/dai/blob/dc9bc577c258e7b4a6e06adb9595257e9f7b85de/src/analysis/domain/octagon.ml#L297

Because of this, the analysis succeeds but produces unsound results. Would it be better to fail rather than silently proceed?

**Comment by bennostein** [comment]
This should be sound if I understand correctly, though quite imprecise to be sure -- it's choosing not to constrain the LHS of the assignment when the maximum environment size is exceeded.

A smarter analysis would have some heuristics to select which variables to include in the environment of the octagon.  We didn't focus much on domain precision here since the papers that correspond to this implementation were much more focused on the incremental analysis engine than the domains themselves.
