### ISSUE TITLE
Build fails: tree_sitter_java not found

### ISSUE THREAD

**Issue by julbinb** [cuplv/dai#7]
I am trying to build the master branch as suggested in the README, but the build fails with

```
File "src/frontend/dune", line 3, characters 23-39:
3 |  (libraries dai syntax tree_sitter_java patience_diff)
                           ^^^^^^^^^^^^^^^^
Error: Library "tree_sitter_java" not found.
```

I am new to Ocaml, so I might be missing something. 
- I've tried `opam install tree_sitter_java`, but the library is not found.
- I've also tried to Google for such a library in Ocaml, but can't find it either.

**Comment by julbinb** [comment]
I've tried `dune install` for the ocaml binding of tree-sitter for java from this repo: https://github.com/semgrep/ocaml-tree-sitter-languages. This creates a library named `tree-sitter-lang.java`, so I replaced `tree_sitter_java` dependency in dai's dune file (in `src/frontend)` with `tree-sitter-lang.java`.

After this, `dune build` for dai fails with 

```
File "src/frontend/src_file.ml", line 8, characters 12-34:
8 | let lines = Ts_src_file.lines
                ^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound value Ts_src_file.lines
```

and indeed I don't see such a function in tree-sitter's `Src_file`.

**Comment by julbinb** [comment]
Okay, it looks like updating `src/run/lib/Src_file.ml` and `src/run/lib/Src_file.mli` of https://github.com/semgrep/ocaml-tree-sitter-core with `let lines x = x.lines` and `val lines : t -> string array`, respectively, allows me to build the project.

**Comment by bennostein** [comment]
Hi Julia, sorry for the slow response that sent you chasing this fix -- I didn't get notifications here.

The patch you applied is exactly what we've done to expose that value on the generated tree sitter module. We had also pinned `ocaml-tree-sitter-languages` at `fc7dd31` for some time here, but if things worked for you at their current version, then great!  I'll get some better instructions in place so that future users don't have to figure out the bit-rot on their own, thanks for the report.
